spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/financetracker
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml
    default-schema: finance_schema